/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LocaleService } from "../locale.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LocaleCreateInput } from "./LocaleCreateInput";
import { LocaleWhereInput } from "./LocaleWhereInput";
import { LocaleWhereUniqueInput } from "./LocaleWhereUniqueInput";
import { LocaleFindManyArgs } from "./LocaleFindManyArgs";
import { LocaleUpdateInput } from "./LocaleUpdateInput";
import { Locale } from "./Locale";
import { PriceFindManyArgs } from "../../price/base/PriceFindManyArgs";
import { Price } from "../../price/base/Price";
import { PriceWhereUniqueInput } from "../../price/base/PriceWhereUniqueInput";
import { ProductMetaFindManyArgs } from "../../productMeta/base/ProductMetaFindManyArgs";
import { ProductMeta } from "../../productMeta/base/ProductMeta";
import { ProductMetaWhereUniqueInput } from "../../productMeta/base/ProductMetaWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LocaleControllerBase {
  constructor(
    protected readonly service: LocaleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Locale",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Locale })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: LocaleCreateInput): Promise<Locale> {
    return await this.service.create({
      data: data,
      select: {
        country: true,
        createdAt: true,
        currency: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Locale",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Locale] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(LocaleFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Locale[]> {
    const args = plainToClass(LocaleFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        country: true,
        createdAt: true,
        currency: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Locale",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Locale })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: LocaleWhereUniqueInput
  ): Promise<Locale | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        country: true,
        createdAt: true,
        currency: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Locale",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Locale })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: LocaleWhereUniqueInput,
    @common.Body() data: LocaleUpdateInput
  ): Promise<Locale | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          country: true,
          createdAt: true,
          currency: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Locale",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Locale })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: LocaleWhereUniqueInput
  ): Promise<Locale | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          country: true,
          createdAt: true,
          currency: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Price",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/prices")
  @ApiNestedQuery(PriceFindManyArgs)
  async findManyPrices(
    @common.Req() request: Request,
    @common.Param() params: LocaleWhereUniqueInput
  ): Promise<Price[]> {
    const query = plainToClass(PriceFindManyArgs, request.query);
    const results = await this.service.findPrices(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,

        locale: {
          select: {
            id: true,
          },
        },

        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Locale",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/prices")
  async connectPrices(
    @common.Param() params: LocaleWhereUniqueInput,
    @common.Body() body: PriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      prices: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Locale",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/prices")
  async updatePrices(
    @common.Param() params: LocaleWhereUniqueInput,
    @common.Body() body: PriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      prices: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Locale",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/prices")
  async disconnectPrices(
    @common.Param() params: LocaleWhereUniqueInput,
    @common.Body() body: PriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      prices: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductMeta",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/productMetas")
  @ApiNestedQuery(ProductMetaFindManyArgs)
  async findManyProductMetas(
    @common.Req() request: Request,
    @common.Param() params: LocaleWhereUniqueInput
  ): Promise<ProductMeta[]> {
    const query = plainToClass(ProductMetaFindManyArgs, request.query);
    const results = await this.service.findProductMetas(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,

        locale: {
          select: {
            id: true,
          },
        },

        metaDescription: true,
        metaTitle: true,

        product: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Locale",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/productMetas")
  async connectProductMetas(
    @common.Param() params: LocaleWhereUniqueInput,
    @common.Body() body: ProductMetaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productMetas: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Locale",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/productMetas")
  async updateProductMetas(
    @common.Param() params: LocaleWhereUniqueInput,
    @common.Body() body: ProductMetaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productMetas: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Locale",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/productMetas")
  async disconnectProductMetas(
    @common.Param() params: LocaleWhereUniqueInput,
    @common.Body() body: ProductMetaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productMetas: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
