/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumLocaleCountry } from "./EnumLocaleCountry";
import { IsEnum, IsOptional, IsString, ValidateNested } from "class-validator";
import { EnumLocaleCurrency } from "./EnumLocaleCurrency";
import { PriceUpdateManyWithoutLocalesInput } from "./PriceUpdateManyWithoutLocalesInput";
import { Type } from "class-transformer";
import { ProductMetaUpdateManyWithoutLocalesInput } from "./ProductMetaUpdateManyWithoutLocalesInput";

@InputType()
class LocaleUpdateInput {
  @ApiProperty({
    required: false,
    enum: EnumLocaleCountry,
    isArray: true,
  })
  @IsEnum(EnumLocaleCountry, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumLocaleCountry], {
    nullable: true,
  })
  country?: Array<"USA" | "Turkey" | "Germany" | "France" | "UK" | "Japan">;

  @ApiProperty({
    required: false,
    enum: EnumLocaleCurrency,
    isArray: true,
  })
  @IsEnum(EnumLocaleCurrency, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumLocaleCurrency], {
    nullable: true,
  })
  currency?: Array<"USD" | "TRY" | "EUR" | "GBP">;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => PriceUpdateManyWithoutLocalesInput,
  })
  @ValidateNested()
  @Type(() => PriceUpdateManyWithoutLocalesInput)
  @IsOptional()
  @Field(() => PriceUpdateManyWithoutLocalesInput, {
    nullable: true,
  })
  prices?: PriceUpdateManyWithoutLocalesInput;

  @ApiProperty({
    required: false,
    type: () => ProductMetaUpdateManyWithoutLocalesInput,
  })
  @ValidateNested()
  @Type(() => ProductMetaUpdateManyWithoutLocalesInput)
  @IsOptional()
  @Field(() => ProductMetaUpdateManyWithoutLocalesInput, {
    nullable: true,
  })
  productMetas?: ProductMetaUpdateManyWithoutLocalesInput;
}

export { LocaleUpdateInput };
