/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumLocaleCountry } from "./EnumLocaleCountry";
import { IsEnum, IsOptional, IsString, ValidateNested } from "class-validator";
import { EnumLocaleCurrency } from "./EnumLocaleCurrency";
import { PriceCreateNestedManyWithoutLocalesInput } from "./PriceCreateNestedManyWithoutLocalesInput";
import { Type } from "class-transformer";
import { ProductMetaCreateNestedManyWithoutLocalesInput } from "./ProductMetaCreateNestedManyWithoutLocalesInput";

@InputType()
class LocaleCreateInput {
  @ApiProperty({
    required: false,
    enum: EnumLocaleCountry,
    isArray: true,
  })
  @IsEnum(EnumLocaleCountry, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumLocaleCountry], {
    nullable: true,
  })
  country?: Array<"USA" | "Turkey" | "Germany" | "France" | "UK" | "Japan">;

  @ApiProperty({
    required: false,
    enum: EnumLocaleCurrency,
    isArray: true,
  })
  @IsEnum(EnumLocaleCurrency, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumLocaleCurrency], {
    nullable: true,
  })
  currency?: Array<"USD" | "TRY" | "EUR" | "GBP">;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => PriceCreateNestedManyWithoutLocalesInput,
  })
  @ValidateNested()
  @Type(() => PriceCreateNestedManyWithoutLocalesInput)
  @IsOptional()
  @Field(() => PriceCreateNestedManyWithoutLocalesInput, {
    nullable: true,
  })
  prices?: PriceCreateNestedManyWithoutLocalesInput;

  @ApiProperty({
    required: false,
    type: () => ProductMetaCreateNestedManyWithoutLocalesInput,
  })
  @ValidateNested()
  @Type(() => ProductMetaCreateNestedManyWithoutLocalesInput)
  @IsOptional()
  @Field(() => ProductMetaCreateNestedManyWithoutLocalesInput, {
    nullable: true,
  })
  productMetas?: ProductMetaCreateNestedManyWithoutLocalesInput;
}

export { LocaleCreateInput };
