/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { OrderUpdateManyWithoutProductsInput } from "./OrderUpdateManyWithoutProductsInput";
import { Type } from "class-transformer";
import { ProductMetaUpdateManyWithoutProductsInput } from "./ProductMetaUpdateManyWithoutProductsInput";
import { ProductVariantUpdateManyWithoutProductsInput } from "./ProductVariantUpdateManyWithoutProductsInput";

@InputType()
class ProductUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => OrderUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => OrderUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => OrderUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  orders?: OrderUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => ProductMetaUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ProductMetaUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ProductMetaUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  productMetas?: ProductMetaUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => ProductVariantUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ProductVariantUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ProductVariantUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  productVariants?: ProductVariantUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  slug?: string | null;
}

export { ProductUpdateInput };
