/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { OrderCreateNestedManyWithoutProductsInput } from "./OrderCreateNestedManyWithoutProductsInput";
import { Type } from "class-transformer";
import { ProductMetaCreateNestedManyWithoutProductsInput } from "./ProductMetaCreateNestedManyWithoutProductsInput";
import { ProductVariantCreateNestedManyWithoutProductsInput } from "./ProductVariantCreateNestedManyWithoutProductsInput";

@InputType()
class ProductCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => OrderCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => OrderCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => OrderCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  orders?: OrderCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => ProductMetaCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ProductMetaCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ProductMetaCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  productMetas?: ProductMetaCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => ProductVariantCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ProductVariantCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ProductVariantCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  productVariants?: ProductVariantCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  slug?: string | null;
}

export { ProductCreateInput };
